import BookshelfMain from './iterator/BookshelfMain'
import AdapterMain from './adapter/AdapterMain'
import TemplateMethodMain from './templateMethod/TemplateMethodMain'
import FactoryMethodMain from './factoryMethod/FactoryMethodMain'
import PrototypeMain from './prototype/Main'
import BuilderMain from './builder/Main'
import AbstractFactoryMain from './abstractfactory/Main'
import BridgeMain from './bridge/Main'
import StrategyMain from './strategy/Main'
import CompositeMain from './composite/Main'
import DecoratorMain from './decorator/Main'
import VisitorMain from './visitor/Main'
import ChainOfResponsibilityMain from './chainofresponsibility/Main'
var main = new ChainOfResponsibilityMain()
